services:
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traffic_data_db
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  pgdata:
